50 questions
What king of Gath provided refuge for David when he was pursued by Saul? (name rhymes with a kebab: Achish)
What enemy of David ravages his temporary homebase of Zilag? (rhymes with something you fly - Amalekites)
Who kills King Saul? (Philitines, bonus: himself as his armor bearers could not bring themselves to comply with Sauls order to finish him)
Who actually liked Saul? (people of Jibesh Gilead; Saul had saved them from the Ammonites and their eye gouging ways; they removed his body from Philistine hands to gave it a proper bury)*
Name two of 4 of Sauls sons (Jonathan, Ishboseth, Armoni, Mephibosheth)
What does the Amalekite tell David when he reports Sauls death? (he finishes a dying Saul off and show him Sauls crown as proof, David executes him)
Whats Abners relationship to Saul? (cousin, New is Sauls uncle)
Who succeeds Saul as king? (IBS)
Where does David assume kingship? (Judah, Hebron: first several sons)
Which of Davids sons are born in Hebron? (Anon, Absalom)
Who does Abner spear? (Ashael)
Who is Ashael related to? (Joab, Abishiah)
Why did Abner defect over to Davids side? (IBS accused him of being with his royal concubines)
Who murders Abner/everyone? (Joab for kiling his bro)
How does IBS go down? (the news of Abners defection causes his regine to capitulate and his own people murder him)
What are some of the first things David does once he enters Jersusalem as king? (fortifies City of David, moves Ark)
What happens when the ark is moved from Baalah (men retrieve it by cart/oxen when the cart breaks and a man touches it to stabalize it he dies so they leave it at Obed Edom for 3 months)
What is Gods reaction to David proposing to build a temple? (God does not need a house)
How does one be a good king? (not too many wives, horses, wealth, obey Him)
How does David honor his friend Jonathan? (he takes in his lame son Mephibosheth)
What is the name of Mephibosheths servant? (Ziba)
Why does David fight the Ammonites? (when King Nahash dies, David sends a delegation to express sympathy to his son who in turn shaves their beards and pants them)
What is the big wrong thing David does? (has affair with Bathsheba and has her husband Uriah the Hittite killed)
Who admonishes him for this? (Nathan the prophet in a story about 2 men and a lamb)
Who is Tamar? (Absaloms sister, Amnons half-sister that he desecrates)
How does Absolom avenge his sister? (invites Amnon to a party-ambush; then flees)
Who brokers the rapproachment between David and his son Absalom? (Joab)
How does Absalom usurt David? (hangs out at the gate and campaigns for himself; builds his power base in his birthplace - Hebron)
Who does David leave in Jerusalem? (Zadok, Abiathar, Ahinoah, Hushai, comcubines)
Who does David leave in Jersualem to run-counter intelligence? (Hushai)
What is the name of the Benjamite troll that harasses Davids group as he leaves? (Shimei)
What does Ziba report about Mephiboseth as David is on his way out? (M is scheming to return the house of Saul to power)
Who is Ahithophel? (Absaloms advisor who advises Absalom to sleep with Davids concubines)
How does Hushai defeat Ahithophel? (advises Absalom to not attack David directly, bide for time; Ahithophel sucides)
How does Absalom go down? (in a showdown with David and Joab gets his luscious hair stuck in a tree and hangs; Joab cuts him a new one)
Who replaces (for a spell) Joab as army commander? (Amasa, why? probably punishment for Joab killing Absalom)
What does Barzillai do? (helps David during his fleeing period to cross the Jordan, is offered to be rewarded when David returns to the throne)
Who is Sheba? (Benjamite that rebels against David soon after he returns to his throne)
Who does David send to subdue Shebas rebellion? (Amasa who is too slow, then Abishai, and be association Joab)
Who regains his old job? (Joab- cuts down Amasa)
Why did the Gibeonites need to be avenged? (they had a long standing non-aggression oauth with the Israelites due to some deception but Saul had violated it and it cropped up as a problem again-one of Sauls decendants was required to be sacraficed to satiate them)
What book of Psalms is 2 Sam 22 equivalent to? (PS 18 which contains Davids distressful calling to the Lord but acknowlegment that the Lord is good to those which are good)
Why was taking a census a bad thing to David to order? (does not rely upon Gods provision, counts own strength)
Who next tries to take over from David as king? (Andonijah - Davids 4th son gathers supporters incl Joab, Abiathar to assume Davids throne)
Who warns David of this plot (Nathan raises this to Bathsheba and Solomon)
How long was Davids reign? (7(J) + 33 (I) = 40)
How does Solomon deal with Abiathar? (no more priest)

